# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Giovanni Licameli
tagline:          'Giovanni Licameli'
description:      'Cyber Security specialist who is drawn to Wireless Penetration Testing, Networking, and high-end technical hardware.'
url:              https://novabutter.github.io
baseurl:          https://novabutter.github.io/

url:              https://novabutter.github.io/
baseurl:          https://novabutter.github.io/

paginate:         5

github:            https://www.github.com/novabutter
linkedin:           https://www.linkedin.com/in/glicameli/
twitter:            # Twitter Handle
website:            # Website